services:
  - type: web
    name: mi-app-laravel
    env: php
    plan: free
    buildCommand: |
      composer install
      npm install
      npm run prod
      php artisan migrate --force
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_KEY
        value: base64:your_app_key
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your_db_host
      - key: DB_PORT
        value: your_db_port
      - key: DB_DATABASE
        value: your_db_name
      - key: DB_USERNAME
        value: your_db_username
      - key: DB_PASSWORD
        value: your_db_password